### ISSUE TITLE
multiple chart images in a single file

### ISSUE THREAD

**Issue by Charlesoxmt** [slightlynybbled/weibull#12]
Request this new feature.
The underlying plotting technology is Matplotlib.  It is possible to save a series of different plots to a single pdf document using inherent Matplotlib capability.
Given a Weibull analysis usually involves looking at the probability plot, the pdf, cdf (or hazard) etc, it seems desirable if these may be optionally output using one document.  Many thanks.

**Comment by slightlynybbled** [comment]
I have been using jupyter notebooks for this type of formatting (see the examples directory, the ipynb file).  I haven't used the matplotlib capability in the past, so I'm not sure what the desired sequence might be.  Could you provide an example matplotlib example of collecting these graphics so that I could more precisely address this requirement?

**Comment by Charlesoxmt** [comment]
Take a look at[ this](https://stackoverflow.com/questions/11328958/matplotlib-pyplot-save-the-plots-into-a-pdf) stack overflow answer

**Comment by slightlynybbled** [comment]
Please see the [`reliability`](https://reliability.readthedocs.io/en/latest/) package for a more feature-rich experience.  I am shifting my work over to that package and will consider the `weibull` package obsolete.
