### ISSUE TITLE
request for fit according to hazard curve

### ISSUE THREAD

**Issue by RyanFunk021** [slightlynybbled/weibull#9]
Can you add a feature that calculates the beta, eta, and blife using the "hazard" distribution?
Caveat:  I have limited knowledge of the calculations, and my question might be nonsensical.

**Comment by slightlynybbled** [comment]
Thank you for your interest!

I'm sure that it can be done, but I'm not sure that I'm the right guy to do it :)

In addition, this is such a niche requirement that I would like to implement other features before tackling this.

In the mean time, if you draw your hazard curve on a sheet, you can use the techniques outlined in the [examples/plot-gen.py](https://github.com/slightlynybbled/weibull/blob/master/examples/plot-gen.py) file and eyeball it yourself.  It would look something like:

    import weibull

    plotter = weibull.Analysis([0], [False])

    plotter.beta = 1.5
    plotter.eta = 100
    plotter.hazard(show=False)

    plotter.beta = 2.0
    plotter.eta = 150
    plotter.hazard()

The above snippet will plot two hazard functions on the same plot so that you can compare.

**Comment by slightlynybbled** [comment]
Please see the [`reliability`](https://reliability.readthedocs.io/en/latest/) package for a more feature-rich experience.  I am shifting my work over to that package and will consider the `weibull` package obsolete.
